-- -- Bootstrap lazy.nvim package manager
-- local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
-- if not vim.loop.fs_stat(lazypath) then
--     vim.fn.system({
--         "git",
--         "clone",
--         "--filter=blob:none",
--         "https://github.com/folke/lazy.nvim.git",
--         "--branch=stable",
--         lazypath,
--     })
-- end
-- vim.opt.rtp:prepend(lazypath)

-- -- Set leader key to space before lazy.nvim loads
-- vim.g.mapleader = " "
-- vim.g.maplocalleader = " "

-- -- Load core configuration
-- require("config.options")
-- require("config.keymaps")
-- require("config.highlights") -- Load custom highlight groups

-- -- Setup lazy.nvim
-- require("lazy").setup("plugins", {
--     change_detection = {
--         notify = false, -- Don't show notifications when plugin files change
--     },
--     install = {
--         colorscheme = { "gruvbox" }, -- Try to load this colorscheme when installing
--     },
--     ui = {
--         border = "single", -- Rounded borders for UI elements
--     },
--     performance = {
--         rtp = {
--             disabled_plugins = {
--                 "gzip",
--                 "matchit",
--                 "matchparen",
--                 "netrwPlugin",
--                 "tarPlugin",
--                 "tohtml",
--                 "tutor",
--                 "zipPlugin",
--             },
--         },
--     },
-- })
